spring.application.name=server

# Database connection settings
spring.datasource.url=jdbc:postgresql://localhost:5432/mangajouka
spring.datasource.username=postgres
spring.datasource.password=password

# Hibernate properties
# 'update' automatically creates/updates tables based on your Java classes
spring.jpa.hibernate.ddl-auto=update

# Shows the actual SQL queries in your console (great for debugging)
spring.jpa.show-sql=true

# Formats the SQL to make it readable
spring.jpa.properties.hibernate.format_sql=true

# Tells Hibernate to use Postgres-specific syntax
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.hibernate.orm.jdbc.bind=TRACE